//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiWeb.TamagotchiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tamagotchi", Namespace="http://schemas.datacontract.org/2004/07/TamagotchiService")]
    [System.SerializableAttribute()]
    public partial class Tamagotchi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GezondheidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HongerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeeftijdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SlaapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VervelingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gezondheid {
            get {
                return this.GezondheidField;
            }
            set {
                if ((this.GezondheidField.Equals(value) != true)) {
                    this.GezondheidField = value;
                    this.RaisePropertyChanged("Gezondheid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Honger {
            get {
                return this.HongerField;
            }
            set {
                if ((this.HongerField.Equals(value) != true)) {
                    this.HongerField = value;
                    this.RaisePropertyChanged("Honger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Leeftijd {
            get {
                return this.LeeftijdField;
            }
            set {
                if ((this.LeeftijdField.Equals(value) != true)) {
                    this.LeeftijdField = value;
                    this.RaisePropertyChanged("Leeftijd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Slaap {
            get {
                return this.SlaapField;
            }
            set {
                if ((this.SlaapField.Equals(value) != true)) {
                    this.SlaapField = value;
                    this.RaisePropertyChanged("Slaap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Verveling {
            get {
                return this.VervelingField;
            }
            set {
                if ((this.VervelingField.Equals(value) != true)) {
                    this.VervelingField = value;
                    this.RaisePropertyChanged("Verveling");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TamagotchiService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTamagotchi", ReplyAction="http://tempuri.org/IService1/GetTamagotchiResponse")]
        TamagotchiWeb.TamagotchiService.Tamagotchi GetTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTamagotchi", ReplyAction="http://tempuri.org/IService1/GetTamagotchiResponse")]
        System.Threading.Tasks.Task<TamagotchiWeb.TamagotchiService.Tamagotchi> GetTamagotchiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTamagotchis", ReplyAction="http://tempuri.org/IService1/GetTamagotchisResponse")]
        TamagotchiWeb.TamagotchiService.Tamagotchi[] GetTamagotchis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTamagotchis", ReplyAction="http://tempuri.org/IService1/GetTamagotchisResponse")]
        System.Threading.Tasks.Task<TamagotchiWeb.TamagotchiService.Tamagotchi[]> GetTamagotchisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTamagotchi", ReplyAction="http://tempuri.org/IService1/AddTamagotchiResponse")]
        void AddTamagotchi(TamagotchiWeb.TamagotchiService.Tamagotchi tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTamagotchi", ReplyAction="http://tempuri.org/IService1/AddTamagotchiResponse")]
        System.Threading.Tasks.Task AddTamagotchiAsync(TamagotchiWeb.TamagotchiService.Tamagotchi tamagotchi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FeedTamagotchi", ReplyAction="http://tempuri.org/IService1/FeedTamagotchiResponse")]
        void FeedTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FeedTamagotchi", ReplyAction="http://tempuri.org/IService1/FeedTamagotchiResponse")]
        System.Threading.Tasks.Task FeedTamagotchiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SleepTamagotchi", ReplyAction="http://tempuri.org/IService1/SleepTamagotchiResponse")]
        void SleepTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SleepTamagotchi", ReplyAction="http://tempuri.org/IService1/SleepTamagotchiResponse")]
        System.Threading.Tasks.Task SleepTamagotchiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PlayTamagotchi", ReplyAction="http://tempuri.org/IService1/PlayTamagotchiResponse")]
        void PlayTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PlayTamagotchi", ReplyAction="http://tempuri.org/IService1/PlayTamagotchiResponse")]
        System.Threading.Tasks.Task PlayTamagotchiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HugTamagotchi", ReplyAction="http://tempuri.org/IService1/HugTamagotchiResponse")]
        int HugTamagotchi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HugTamagotchi", ReplyAction="http://tempuri.org/IService1/HugTamagotchiResponse")]
        System.Threading.Tasks.Task<int> HugTamagotchiAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TamagotchiWeb.TamagotchiService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TamagotchiWeb.TamagotchiService.IService1>, TamagotchiWeb.TamagotchiService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TamagotchiWeb.TamagotchiService.Tamagotchi GetTamagotchi(int id) {
            return base.Channel.GetTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task<TamagotchiWeb.TamagotchiService.Tamagotchi> GetTamagotchiAsync(int id) {
            return base.Channel.GetTamagotchiAsync(id);
        }
        
        public TamagotchiWeb.TamagotchiService.Tamagotchi[] GetTamagotchis() {
            return base.Channel.GetTamagotchis();
        }
        
        public System.Threading.Tasks.Task<TamagotchiWeb.TamagotchiService.Tamagotchi[]> GetTamagotchisAsync() {
            return base.Channel.GetTamagotchisAsync();
        }
        
        public void AddTamagotchi(TamagotchiWeb.TamagotchiService.Tamagotchi tamagotchi) {
            base.Channel.AddTamagotchi(tamagotchi);
        }
        
        public System.Threading.Tasks.Task AddTamagotchiAsync(TamagotchiWeb.TamagotchiService.Tamagotchi tamagotchi) {
            return base.Channel.AddTamagotchiAsync(tamagotchi);
        }
        
        public void FeedTamagotchi(int id) {
            base.Channel.FeedTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task FeedTamagotchiAsync(int id) {
            return base.Channel.FeedTamagotchiAsync(id);
        }
        
        public void SleepTamagotchi(int id) {
            base.Channel.SleepTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task SleepTamagotchiAsync(int id) {
            return base.Channel.SleepTamagotchiAsync(id);
        }
        
        public void PlayTamagotchi(int id) {
            base.Channel.PlayTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task PlayTamagotchiAsync(int id) {
            return base.Channel.PlayTamagotchiAsync(id);
        }
        
        public int HugTamagotchi(int id) {
            return base.Channel.HugTamagotchi(id);
        }
        
        public System.Threading.Tasks.Task<int> HugTamagotchiAsync(int id) {
            return base.Channel.HugTamagotchiAsync(id);
        }
    }
}
