//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagot
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Leeftijd { get; set; }
        public int Honger { get; set; }
        public int Slaap { get; set; }
        public int Verveling { get; set; }
        public int Gezondheid { get; set; }
    }
}
